# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: mac_agent
      demands: agent.name -equals Pradeeps-Air 
    steps:
    - script: echo "Running on self-hosted agent!"
      displayName: "Test self-hosted agent"
    
    - script: |
        echo "Java version:"
        java -version
      displayName: 'Check Java Version'
      env:
        JAVA_HOME: /opt/homebrew/opt/openjdk@17
        PATH: /opt/homebrew/opt/openjdk@17/bin:$(PATH)

    - script: java -version
      displayName: 'Verify Java Version'

    - script: mvn clean install  # or ./gradlew build
      displayName: 'Build the project'
    
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'mvn clean package -DskipTests'

    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/springboot-hello-world/Dockerfile'
        tags: |
          $(tag)
